[package]
name = "serialization"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
serde_json = "1"

[dependencies.splines]
version = "0.1"
features = ["serialization"]
